export const SELECT_EXCHANGE = 'SELECT_EXCHANGE';
export const DESELECT_EXCHANGE = 'DESELECT_EXCHANGE';
export const CLEAR_EXCHANGES = 'CLEAR_EXCHANGES';
export const ADD_EXCHANGES = 'ADD_EXCHANGES';
export const SET_PRESELECTED = 'SET_PRESELECTED';

export const SET_GOOGLE_MAPS_API = 'SET_GOOGLE_MAPS_API';
export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
