export const SELECT_EXCHANGE = 'SELECT_EXCHANGE';
export const DESELECT_EXCHANGE = 'DESELECT_EXCHANGE';
export const CLEAR_EXCHANGES = 'CLEAR_EXCHANGES';
export const ADD_EXCHANGES = 'ADD_EXCHANGES';
export const SET_EXCHANGES = 'SET_EXCHANGES';

export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';

export const SET_SEARCH_PARAMS= 'SET_SEARCH_PARAMS';
export const CLEAR_SEARCH_PARAMS = 'CLEAR_SEARCH_PARAMS';
