export const SELECT_EXCHANGE = 'SELECT_EXCHANGE';
export const DESELECT_EXCHANGE = 'DESELECT_EXCHANGE';

export const MARKER_IS_OPENED = 'MARKER_IS_OPENED';

export const SET_GOOGLE_MAPS_API = 'SET_GOOGLE_MAPS_API';